version: '3.9'

services:
  app:
    image: 'movieapi:latest'
    build:
      context: .
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - "9595-9597:8080"
    networks:
      movie-api-network:

  # Actuatorun okuduğu verileri(metric) anlamlı hale getirir
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      movie-api-network:

  # Prometheusdaki verileri fonksiyonel hale getirip grafik ve alert oluşturur
  grafana:
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITIY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    networks:
      movie-api-network:

networks:
  movie-api-network: